* [X] Create L1-5 keycards with relevant textures (sent above on Discord)
* [X] Pair keycards to the corresponding “reader” skulls (in the center of the research commons area)
* [X] Make sure keycards function properly (ex. L3s can open L1 and L2-required doors)
* [X] Set the voicelines and subsequent flickers, etc. to occur at the designated zones (there should be diamond blocks with signs in the research bunking area that talks about it).
* [X] Remove title card in the “blackout” and time the blackout time with the audio
* [X] Update the intro voicelines to the new ones (sent below on Discord)
* [C] Make it so if you right-click a flint item that is in your inventory, it will set your spawn point to where you are (a sort of save function) and say in chat— &9[Save point set.] I will retexture it sometime.
* [X] Change L1 card texture to this, since the current one has the "1" far too large and it irks me. It is irksome.
* [X] Make it so keycard readers will either tell you in actionbar near inventory “[Access Granted]”, or “[Access Denied—L3+ Card Required]”, or whatever L# the reader is
* [X] Implement the keycard accepted/door open sound (sent on Discord)
* [X] Implement the keycard denied sound (sent on Discord)
* [X] Also, hitting this button will clear their inventory and give them only one item—their L1 Card.
* [X] It can then spawn the player in their bunk and start the game.
* [X] Tutorial center is now done—the button at the very end of the hall should put the player(s) in spectator mode, black out the screen—and small white titles on the screen should say “0853 Hours. 15th of April, 2012. Northern Seattle.”
* [X] tp far away players in s2 cutscene
* [C] Teslagates - make ‘em. There is the frame of one in the tutorial center. Make it so it activates if any player is within 10 blocks of it (electricity through it, the usual). It activates once every 3 seconds. If the player is standing in it when it activates, instant death.
* [C] glow outline with the thing in mc cmds discord (on card readers)
* [X] Make it so in the intro, when the bridge falls and just before the blackout, explosion particles are summoned on the player (give it a sense of “o yeah, that’s what knocked me out and not the collapse of a platform I’m observing from a distance”)—can give it the explosion sound too if you want
* [X] figure out why first join detection isnt working properly
* [X] include door playsound in antispam
* [X] rifle
* [X] S H O W E R S
* [X] vents
* [C] investigate choppy introatrium start
* [X] pistol
* [X] Difficulty setting
* [X] Change player spawn
* [X] Add PA broadcast https://cdn.discordapp.com/attachments/698688605320773703/740634667845156884/PelleaJerniganPA.ogg
* [X] https://cdn.discordapp.com/attachments/726903192956174432/740390043130003486/unknown.png fix so it fits on all screens regardless of res -- also test
* [X] Teslagates
* [X] Voice line captions
* [X] voicelog
* [C] Working elevators for containment levels
* [X] checkpoints
* [X] feedback for checkpoints
* [X] Add following voicelines to game: PelleaLoop, DavisRadio1, Radio_Call, RadioPlight1, DavisTeslagates
* [X] Add rifle model in place of bow—needed for film shots
* [X] Make blackout as soon as player hits the water for the cavern
* [X] Teleports player to the water pit at the end of the shafts after 10 seconds
* [X] Make the "TunnelsVoiceline1" play 5 seconds after entering the actual shafts themselves
* [X] bridve fall at /execute in minecraft:overworld run tp
* [X] All voiceline subtitles (intro) are borked
* [X] Endler's voicelog is bork, doesn't even play
* [X] Need to update Richthofen's voicelines with new ones
* [C] Remove the "Falling From Grace" thing from blackout
* [X] Hide "game mode set to ___" during blackout
* [X] Have SCP-999 give the player basic jump boost 1 and resistance 1 when the player is within 5 blocks of it
* [C] fix bug where jumping/moving sideways while opening keycard door only opens some of the door
* [X] make s80 sound trigger position-based once they get in the vents a bit instead of time-based (also make sure to account ofr the way where u swim into the thingy with the hidden one)
* [C] scripted voicelogs
* [C] fix scp109 (every splash pot behaves like it, not only certain items)
* [X] revert slimeball texture to old elly one as its inconsistent as slimeball is currently crazy's
* [C] optimize serverside doors cause https://i.ronthecookie.me/6AOz4VR.png
* [X] dont get outsmarted when player is moving too fast (s17 can start early)
* [X] finish deadjb (jernigan blood) model
* [X] airlocks (~door retrofit~ normal mc doors)
	/execute in minecraft:overworld run tp
* [X] fix lag problems `https://discord.com/channels/
* [X] remove yalm cmd blocks and convert into proper airlock once those are done `/execute in minecraft:overworld run tp
* [X] Working trains that move
* [X] get star to make {vents,teslagate} sfx
* [C] finish rorkefall (sucky sucky by scp)
need star to make keyframes and get audio
* [X] get star to make fem dead skin so it goes along with scp970 barrel structure (has a fem voicelog but male corpse)

* Ready To Do
** [ ] fix entity leak from bridve, probably bridve-wasmoving or something like it but aecs with no tags just keep on stacking up at the end of the part of the bridge that falls
** [ ] don't trigger ambience on (re)load
it'll get problematic once they are in singleplayer and load the save while in a stage with lots of ambience on
** [ ] rework guns to use loot tables instead (for ~guns/update_item~), maybe less lag
** [ ] avoid using @x[score=]: https://minecraftcommands.github.io/commanders-handbook/selector-argument-order
** [ ] make door system not leak falling_block's all the time

* Discussion Required
** [ ] think about ways to make s10 no goal complete -> s17 transition smoother
*** [ ] rn it [bossbar] just disappears and its awkward imo
https://i.ronthecookie.me/uUa0iLc.png

* Long-term Things
** [ ] death msgs
*** use https://github.com/rx-modules/PlayerMatch
** [ ] use this datapack to make sure players don't do silly things https://github.com/Razboy20/version-proxy-mc-datapack
** [ ] see what we can use advancements for instead of detecting certain events manually (stuff like scores for CoaS right click)
* Pre-release checklist
**  Use this: https://github.com/shurik204/map-prepare
** [ ] cleanup {data,resource}pack errors in logs (e.g. AnyFallingBlock, missing sound)
** [ ] ensure subtitle coverage with absub/genload
** [ ] graphics quality interactable sign in lobby that adjusts flicker time and other things to reduce fps lag
** [ ] balance/normalize all the audio levels so theres not super super loud parts
** [ ] prune chunks at end https://gist.github.com/onnowhere/48655f2cac8a2c6cb5aac308ea89360c
** [ ] ensure entire game has subs
** [ ] make s10 task not cheatable by returning item
** [ ] remove dev.* sounds (from osu! lol)

* next map ideas:
** crossbow aerial combat? (maybe on star's boats and one person stationary one in air)
** (lingering) potion throw competitive (to kill other players, could be 2 teams one in slow tankish flying heli or whatever and other in elytras)
** potion throwing how far away can you throw
