const fs = require("fs");
const HEADER = "# This is the autogenerated output of poser.js.";

const count = n => [...Array(n).keys()];
const eachComb = f => combinations.map(f).join("\n");
const poseParts = ["Body", "Head", "LeftLeg", "RightLeg", "LeftArm", "RightArm"];
const intScale = Math.pow(10, 5); // keep 5 decimal digits of accuracy for user math

// Pos[3], Pose[6x3], Rotation[2]
const combinations = [
	...count(3).map(x => `Pos[${x}]`),
	...count(2).map(x => `Rotation[${x}]`),
	...poseParts.map(x => count(3).map(y => `Pose.${x}[${y}]`)).reduce((a, b) => [...a, ...b])
];

fs.writeFileSync(
	require("path").join(
		__dirname,
		"data",
		"arc86",
		"functions",
		"poser",
		"collect.mcfunction"
	), `${HEADER}
${eachComb(path => `execute store result score ${path} poser run data get entity @s ${path} ${intScale}`)}
`,
	{ encoding: "utf8" }
)

fs.writeFileSync(
	require("path").join(
		__dirname,
		"data",
		"arc86",
		"functions",
		"poser",
		"apply.mcfunction"
	), `${HEADER}
${eachComb(path => `execute store result entity @s ${path} float ${1/intScale} run scoreboard players get ${path} poser`)}
`,
	{ encoding: "utf8" }
)
