const fs = require("fs");
let output = "# This is the autogenerated output of shake_s100.js, used primarily for s100.\n";

const shakeAmount = 2;
for (let i = 0; i < 100; i++) {
	[0, 0].map(x => Math.round((Math.random() * shakeAmount * 2) - shakeAmount)).forEach((x, j) => {
		const score = j == 0 ? "valX" : "valY";
		output += `execute if score @s shake_s100 matches ${i * 2} run scoreboard players ${x > 0 ? "add" : "remove"} $${score} s100 ${Math.abs(x)}\n`;
		x = -x;
		output += `execute if score @s shake_s100 matches ${i * 2 + 1} run scoreboard players ${x > 0 ? "add" : "remove"} $${score} s100 ${Math.abs(x)}\n`;
    });
}

output += `execute if score @s shake_s100 matches 201.. run scoreboard players set @s shake_s100 -1\n`
output += "scoreboard players add @s shake_s100 1\n";

fs.writeFileSync(
	require("path").join(
		__dirname,
		"data",
		"arc86",
		"functions",
		"shake",
		"genshakes100.mcfunction"
	), output,
	{ encoding: "utf8" }
)
