const fs = require("fs");
let output = "# This is the autogenerated output of shake_xyz.js\n";

const shakeAmount = 0.1;
for (let i = 0; i < 100; i++) {
	const xyz = [0, 0, 0].map(x => (Math.random() * shakeAmount * 2) - shakeAmount)
	output += `execute if score @s shake_xyz matches ${i} run tp @s ${xyz.map(x => `~${x}`).join(" ")}\n`
}

output += `execute if score @s shake_xyz matches 101.. run scoreboard players set @s shake_xyz -1\n`
output += "scoreboard players add @s shake_xyz 1\n";

fs.writeFileSync(
	require("path").join(
		__dirname,
		"data",
		"arc86",
		"functions",
		"shake",
		"genshakexyz.mcfunction"
	), output,
	{ encoding: "utf8" }
)
