const fs = require("fs");
let output = "# This is the autogenerated output of shake.js\n";

// let lastRot = [0, 0];
const shakeAmount = 2;
for (let i = 0; i < 100; i++) {
	const rot = [0, 0].map(x => (Math.random() * shakeAmount * 2) - shakeAmount)
	output += `execute if score @s trainshake matches ${i} run tp @s ~ ~ ~ ~${rot[0]} ~${rot[1]}\n`
	// lastRot = rot;
}

output += `execute if score @s trainshake matches 101.. run scoreboard players set @s trainshake -1\n`
output += "scoreboard players add @s trainshake 1\n";

fs.writeFileSync(
	require("path").join(
		__dirname,
		"data",
		"arc86",
		"functions",
		"trainshake",
		"genshake.mcfunction"
	), output,
	{ encoding: "utf8" }
)
