const fs = require("fs");
let output = "# This is the autogenerated output of shake_xz.js, used primarily for s100.\n";

const shakeAmount = 0.005;
for (let i = 0; i < 100; i++) {
	const xz = [0, 0, 0].map(x => (Math.random() * shakeAmount * 2) - shakeAmount).map((x, i) => i == 1 ? 0 : x);
	output += `execute if score @s shake_xz matches ${i * 2} run tp @s ${xz.map(x => `~${x}`).join(" ")}\n`
	output += `execute if score @s shake_xz matches ${i * 2 + 1} run tp @s ${xz.map(x => `~${-x}`).join(" ")}\n`
}

output += `execute if score @s shake_xz matches 201.. run scoreboard players set @s shake_xz -1\n`
output += "scoreboard players add @s shake_xz 1\n";

fs.writeFileSync(
	require("path").join(
		__dirname,
		"data",
		"arc86",
		"functions",
		"shake",
		"genshakexz.mcfunction"
	), output,
	{ encoding: "utf8" }
)
