//@ts-check
const fs = require("fs");
const sounds = require("../resourcepack/assets/arc86/sounds.json");
const postLines = [];
const lines = Object.keys(sounds).map(key => {
	const { voicelog } = sounds[key];
	if (!voicelog) return;
	return `execute if score $current voicelogSoundId matches ${voicelog} run playsound arc86:${key} voice @a[distance=..10] ~ ~ ~ 1 1 1`;
});

const out = `# Auto-generated by voicelog.js
# Edit sounds.json def and rerun to edit

${lines.join("\n")}

${postLines.join("\n")}

`;

fs.writeFileSync(
	require("path").join(
		__dirname,
		"data",
		"arc86",
		"functions",
		"voicelogs",
		"genps.mcfunction"
	),
	out,
	{ encoding: "utf8" }
);
