# Auto-generated by voicelog.js
# Edit sounds.json def and rerun to edit

execute if score @s currentVoicelog matches 6 if score @s voicelogTime matches 1140.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 8 if score @s voicelogTime matches 620.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 9 if score @s voicelogTime matches 146.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 10 if score @s voicelogTime matches 353.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 11 if score @s voicelogTime matches 5.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 12 if score @s voicelogTime matches 5.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 13 if score @s voicelogTime matches -1.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 13 if score @s voicelogTime matches 5.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 14 if score @s voicelogTime matches 5.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 15 if score @s voicelogTime matches 5.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 16 if score @s voicelogTime matches 5.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 17 if score @s voicelogTime matches 5.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 18 if score @s voicelogTime matches 5.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 18 if score @s voicelogTime matches 5.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 19 if score @s voicelogTime matches 766.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 20 if score @s voicelogTime matches 973.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 21 if score @s voicelogTime matches 1005.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 22 if score @s voicelogTime matches 680.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 23 if score @s voicelogTime matches 500.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 24 if score @s voicelogTime matches 1160.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 25 if score @s voicelogTime matches 920.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 26 if score @s voicelogTime matches 1100.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 27 if score @s voicelogTime matches 940.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 28 if score @s voicelogTime matches 920.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 29 if score @s voicelogTime matches 560.. run function arc86:voicelogs/ps_over

