# Auto-generated by voicelog.js
# Edit sounds.json def and rerun to edit
scoreboard players set @s voicelogTime 0

execute if score @s currentVoicelog matches 6 run playsound arc86:voicelogs.endler voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 8 run playsound arc86:voicelogs.rorkecafe voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 9 run playsound arc86:voicelogs.lobby voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 10 run playsound arc86:voicelogs.klein109 voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 11 run playsound arc86:voicelogs.lczplea voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 12 run playsound arc86:voicelogs.richopsdeath voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 13 run playsound arc86:s85 voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 13 run playsound arc86:voicelogs.davishelp voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 14 run playsound arc86:voicelogs.jamiefemradio voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 15 run playsound arc86:voicelogs.pelleannounce voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 16 run playsound arc86:voicelogs.sadopsradio voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 17 run playsound arc86:voicelogs.teslagategobrr voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 18 run playsound arc86:dev.sectionfail voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 18 run playsound arc86:dev.sectionpass voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 19 run playsound arc86:voicelogs.artu1 voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 20 run playsound arc86:voicelogs.artu2 voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 21 run playsound arc86:voicelogs.artu3 voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 22 run playsound arc86:voicelogs.maxwell121 voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 23 run playsound arc86:voicelogs.maxwell999 voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 24 run playsound arc86:voicelogs.maxwelltheory voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 25 run playsound arc86:voicelogs.morriganboom voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 26 run playsound arc86:voicelogs.anandsuicide voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 27 run playsound arc86:voicelogs.wallace1 voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 28 run playsound arc86:voicelogs.wallace2 voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 29 run playsound arc86:voicelogs.davisworried voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 30 run playsound arc86:dev.slightlyhqmo voice @s ~ ~ ~ 1 1 1
execute if score @s currentVoicelog matches 31 run playsound arc86:airlock voice @s ~ ~ ~ 1 1 1

