# Auto-generated by voicelog.js
# Edit sounds.json def and rerun to edit

execute if score @s currentVoicelog matches 6 if score @s voicelogTime matches 1140.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 8 if score @s voicelogTime matches 620.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 9 if score @s voicelogTime matches 146.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 10 if score @s voicelogTime matches 353.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 11 if score @s voicelogTime matches 5.. run function arc86:voicelogs/ps_over
execute if score @s currentVoicelog matches 12 if score @s voicelogTime matches 5.. run function arc86:voicelogs/ps_over

