# Auto-generated by voicelog.js
# Edit sounds.json def and rerun to edit
scoreboard players set $time voicelog 0

execute if score $current voicelog matches 6 run playsound arc86:voicelogs.endler voice @a[distance=..10] ~ ~ ~ 1 1 1
execute if score $current voicelog matches 8 run playsound arc86:voicelogs.rorkecafe voice @a[distance=..10] ~ ~ ~ 1 1 1
execute if score $current voicelog matches 9 run playsound arc86:voicelogs.lobby voice @a[distance=..10] ~ ~ ~ 1 1 1

