# Auto-generated by version.js
execute positioned -108 152 31 run title @a[distance=..50] actionbar [{"text":"srv="},{"text":"039fd18","color":"red"},{"text":" | ","color":"dark_gray"},{"text":"client=","color":"white"},{"translate":"arc86.version","color":"red"}]
