# Auto-generated by absub.js
# Edit sounds.json def and rerun to edit

tellraw @a "[!] Missing absub for s50"
tellraw @a "[!] Missing absub for voicelogs.rorkecafe"
tellraw @a "[!] Missing absub for voicelogs.lobby"
tellraw @a "[!] Missing absub for voicelogs.lczplea"
tellraw @a "[!] Missing absub for voicelogs.richopsdeath"
tellraw @a "[!] Missing absub for voicelogs.davishelp"
tellraw @a "[!] Missing absub for voicelogs.jamiefemradio"
tellraw @a "[!] Missing absub for voicelogs.pelleannounce"
tellraw @a "[!] Missing absub for voicelogs.sadopsradio"
tellraw @a "[!] Missing absub for voicelogs.teslagategobrr"
tellraw @a "[!] Missing absub for voicelogs.artu3"
tellraw @a "[!] Missing absub for voicelogs.maxwell121"
tellraw @a "[!] Missing absub for voicelogs.maxwell999"
tellraw @a "[!] Missing absub for voicelogs.maxwelltheory"
tellraw @a "[!] Missing absub for voicelogs.anandsuicide"
tellraw @a "[!] Missing absub for voicelogs.wallace1"
tellraw @a "[!] Missing absub for voicelogs.wallace2"
tellraw @a "[!] Missing absub for voicelogs.davisworried"

