# Auto-generated by absub.js
# Edit sounds.json def and rerun to edit

execute if score $id absubState matches 10 if score $time absubState matches 1..14 run title @a actionbar [{"text":"FartMan","bold":true},{"text":": ","bold":true},{"text":"Y u fart on my bed","bold":false}]
execute if score $id absubState matches 10 if score $time absubState matches 15 run title @a actionbar [{"text":"PoopMan","bold":true},{"text":": ","bold":true},{"text":"why not?","bold":false}]

execute if score $id absubState matches 10 if score $time absubState matches 15 run function arc86:absub/reset

