# Auto-generated by absub.js
# Edit sounds.json def and rerun to edit

execute if score $id absubState matches 1 if score $time absubState matches 1520..1599 run title @a actionbar [{"text":"Fiorillo","bold":true},{"text":": ","bold":true},{"text":"Preston?","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 1600..1639 run title @a actionbar [{"text":"Fiorillo","bold":true},{"text":": ","bold":true},{"text":"Preston...","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 1640..1659 run title @a actionbar [{"text":"Fiorillo","bold":true},{"text":": ","bold":true},{"text":"Preston, get the hell over here.","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 1660..1699 run title @a actionbar [{"text":"Fiorillo","bold":true},{"text":": ","bold":true},{"text":"I told you 'Wake up on time, cmon'","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 1700..1759 run title @a actionbar [{"text":"Fiorillo","bold":true},{"text":": ","bold":true},{"text":"and you fall right back to sleep again.","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 1760..1799 run title @a actionbar [{"text":"Fiorillo","bold":true},{"text":": ","bold":true},{"text":" I don’t even know why I bother.","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 1800..1839 run title @a actionbar [{"text":"Fiorillo","bold":true},{"text":": ","bold":true},{"text":"Hurry up!","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 1840..1899 run title @a actionbar [{"text":"Fiorillo","bold":true},{"text":": ","bold":true},{"text":"Scientific atrium. Or else Heermann’ll be pissed.","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 1900..1919 run title @a actionbar [{"text":"Fiorillo","bold":true},{"text":": ","bold":true},{"text":"Again!","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 1920..1959 run title @a actionbar [{"text":"Steven","bold":true},{"text":": ","bold":true},{"text":"Oh well, Preston -","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 1960..1979 run title @a actionbar [{"text":"Steven","bold":true},{"text":": ","bold":true},{"text":"This is Steven","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 1980..1999 run title @a actionbar [{"text":"Steven","bold":true},{"text":": ","bold":true},{"text":"with a V.","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 2000..2059 run title @a actionbar [{"text":"Steven","bold":true},{"text":": ","bold":true},{"text":"I, ugh, I think I might have left my medication","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 2060..2119 run title @a actionbar [{"text":"Steven","bold":true},{"text":": ","bold":true},{"text":"...in my room, can you, ugh","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 2120..2159 run title @a actionbar [{"text":"Steven","bold":true},{"text":": ","bold":true},{"text":"Can you bring that?","bold":false}]
execute if score $id absubState matches 1 if score $time absubState matches 2160 run title @a actionbar [{"text":"Steven","bold":true},{"text":": ","bold":true},{"text":"Thanks.","bold":false}]
execute if score $id absubState matches 2 if score $time absubState matches 20..59 run title @a actionbar [{"text":"Pellea","bold":true},{"text":": ","bold":true},{"text":"Good morning, eight-six","bold":false}]
execute if score $id absubState matches 2 if score $time absubState matches 60..159 run title @a actionbar [{"text":"Pellea","bold":true},{"text":": ","bold":true},{"text":"Standard morning shift briefings are to take place in five minutes, department centers.","bold":false}]
execute if score $id absubState matches 2 if score $time absubState matches 160..279 run title @a actionbar [{"text":"Pellea","bold":true},{"text":": ","bold":true},{"text":"Night shift is officially relieved as of now; try and get some rest.","bold":false}]
execute if score $id absubState matches 2 if score $time absubState matches 280..359 run title @a actionbar [{"text":"Pellea","bold":true},{"text":": ","bold":true},{"text":"Division heads, expect a visit from Ethics Committee at eleven-hundred hours.","bold":false}]
execute if score $id absubState matches 2 if score $time absubState matches 360..439 run title @a actionbar [{"text":"Pellea","bold":true},{"text":": ","bold":true},{"text":"Now hear this","bold":false}]
execute if score $id absubState matches 2 if score $time absubState matches 440..499 run title @a actionbar [{"text":"Jernigan","bold":true},{"text":": ","bold":true},{"text":" This is Assistant Site Director Sita Jernigan.","bold":false}]
execute if score $id absubState matches 2 if score $time absubState matches 500..599 run title @a actionbar [{"text":"Jernigan","bold":true},{"text":": ","bold":true},{"text":"I expect site security teams alpha through echo at main gate for cycle out.","bold":false}]
execute if score $id absubState matches 2 if score $time absubState matches 600 run title @a actionbar [{"text":"Jernigan","bold":true},{"text":": ","bold":true},{"text":"Site security teams alpha through echo. Ten minutes. Be fleet.","bold":false}]
execute if score $id absubState matches 3 if score $time absubState matches 80..119 run title @a actionbar [{"text":"Richthofen","bold":true},{"text":": ","bold":true},{"text":"All personnel, set Condition Yellow,","bold":false}]
execute if score $id absubState matches 3 if score $time absubState matches 120..159 run title @a actionbar [{"text":"Richthofen","bold":true},{"text":": ","bold":true},{"text":"I repeat, set condition yellow.","bold":false}]
execute if score $id absubState matches 3 if score $time absubState matches 160..219 run title @a actionbar [{"text":"Richthofen","bold":true},{"text":": ","bold":true},{"text":"We have lost main power in the site,","bold":false}]
execute if score $id absubState matches 3 if score $time absubState matches 220..259 run title @a actionbar [{"text":"Richthofen","bold":true},{"text":": ","bold":true},{"text":"Backup generators are starting up,","bold":false}]
execute if score $id absubState matches 3 if score $time absubState matches 260 run title @a actionbar [{"text":"Richthofen","bold":true},{"text":": ","bold":true},{"text":"Stand by.","bold":false}]
execute if score $id absubState matches 4 if score $time absubState matches 80..103 run title @a actionbar [{"text":"Richthofen","bold":true},{"text":": ","bold":true},{"text":"All personnel, be advised.","bold":false}]
execute if score $id absubState matches 4 if score $time absubState matches 104..139 run title @a actionbar [{"text":"Richthofen","bold":true},{"text":": ","bold":true},{"text":"All electrical systems have failed.","bold":false}]
execute if score $id absubState matches 4 if score $time absubState matches 140..191 run title @a actionbar [{"text":"Richthofen","bold":true},{"text":": ","bold":true},{"text":"Containment may not be feasible.","bold":false}]
execute if score $id absubState matches 4 if score $time absubState matches 192 run title @a actionbar [{"text":"Richthofen","bold":true},{"text":": ","bold":true},{"text":"Stan-","bold":false}]
execute if score $id absubState matches 5 if score $time absubState matches 113..167 run title @a actionbar [{"text":"E.C.S","bold":true},{"text":": ","bold":true},{"text":"This is a Code Red containment breach alert.","bold":false}]
execute if score $id absubState matches 5 if score $time absubState matches 168..257 run title @a actionbar [{"text":"E.C.S","bold":true},{"text":": ","bold":true},{"text":"All personnel, set your stations to condition one.","bold":false}]
execute if score $id absubState matches 5 if score $time absubState matches 258..321 run title @a actionbar [{"text":"E.C.S","bold":true},{"text":": ","bold":true},{"text":"Site security is to immediately attempt recontainment procedures.","bold":false}]
execute if score $id absubState matches 5 if score $time absubState matches 322..377 run title @a actionbar [{"text":"E.C.S","bold":true},{"text":": ","bold":true},{"text":"All other non-essential personnel.","bold":false}]
execute if score $id absubState matches 5 if score $time absubState matches 378 run title @a actionbar [{"text":"E.C.S","bold":true},{"text":": ","bold":true},{"text":"Evacuate Site-86 at once.","bold":false}]
execute if score $id absubState matches 10 if score $time absubState matches 0..24 run title @a actionbar [{"text":"rambo","bold":true},{"text":": ","bold":true},{"text":"i farted!!!","bold":false}]
execute if score $id absubState matches 10 if score $time absubState matches 25..32 run title @a actionbar [{"text":"threepenny","bold":true},{"text":": ","bold":true},{"text":"i didnt fart","bold":false}]
execute if score $id absubState matches 10 if score $time absubState matches 33 run title @a actionbar [{"text":"two four gayming","bold":true},{"text":": ","bold":true},{"text":"i am obese","bold":false}]

execute if score $id absubState matches 1 if score $time absubState matches 2160 run function arc86:absub/reset
execute if score $id absubState matches 2 if score $time absubState matches 600 run function arc86:absub/reset
execute if score $id absubState matches 3 if score $time absubState matches 260 run function arc86:absub/reset
execute if score $id absubState matches 4 if score $time absubState matches 192 run function arc86:absub/reset
execute if score $id absubState matches 5 if score $time absubState matches 378 run function arc86:absub/reset
execute if score $id absubState matches 10 if score $time absubState matches 33 run function arc86:absub/reset

