# Auto-generated by absub.js
# Edit sounds.json def and rerun to edit

execute if score $id absubState matches 10 if score $time absubState matches 0..24 run title @a actionbar [{"text":"rambo","bold":true},{"text":": ","bold":true},{"text":"i farted!!!","bold":false}]
execute if score $id absubState matches 10 if score $time absubState matches 25..32 run title @a actionbar [{"text":"threepenny","bold":true},{"text":": ","bold":true},{"text":"i didnt fart","bold":false}]
execute if score $id absubState matches 10 if score $time absubState matches 33 run title @a actionbar [{"text":"xxxxxxxxxxone two four gayming","bold":true},{"text":": ","bold":true},{"text":"i am obese","bold":false}]

execute if score $id absubState matches 10 if score $time absubState matches 33 run function arc86:absub/reset

